# WitherBlocker Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/WitherBlocker

#==================#
#   Basic Config   #
#==================#
# none :3

#========================#
#   Permissions Config   #
#========================#
# Use Permissions List
Permissions:
- vault
- pex
- superperms
- ops

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1