# WitherBlocker Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/WitherBlocker

#==================#
#   Basic Config   #
#==================#
WhiteWorlds:
- this_is_a
- white_world

CancelWitherSpawnEvent: true
DeniedMessage: '&cYou do not have permission to do this!'

#==================#
#   Other Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1